
language: cpp

compiler:
  - gcc
  
env:
  - TRAVIS_NODE_VERSION="4"

dist: trusty

sudo: required


before_script:
  - chmod +x ./build.*

script:
  - nodejs --version
  - ./build.linux64.sh
  
notifications:
  email:
    on_failure: change
