
language: cpp

sudo: required

compiler:
  - gcc
  
addons:
  apt:
      sources:
          - ubuntu-toolchain-r-test
      packages:
          - cmake

# Install cmake and npm/nodejs
before_install:
  - sudo apt-get install -qq npm

before_script:
  - chmod +x ./build.*

script:
  - ./build.linux64.sh
  
notifications:
  email:
    on_failure: change
