
language: cpp

node_js:
  - "4.2"

dist: trusty

sudo: required

compiler:
  - gcc
  
before_script:
  - chmod +x ./build.*

script:
  - ./build.linux64.sh
  
notifications:
  email:
    on_failure: change
