
image: Visual Studio 2015

version: 1.0.{build}

branches:
  only:
    - master

max_jobs: 1

install:
  - npm install -g node-gyp

platform:
  - x86

build_script:
  - python build.py --build_config=release  --skip_tests

test_script:
  - cmd: cd install_release_x86; ppp-tests.exe --gtest_filter=-*TestEndToEndLandmarkDetection* --gtest_output=xml:tests.xml